### PR TITLE
Make it compatible with react 0.15.0-rc peerDependency

### PR DESCRIPTION
**Pull request by ababol**
Otherwise there is some trouble during npm install :no_good:

### CODE REVIEW

**Comment by grabbou** [comment]
Thanks! Yeah, these constraints do not work with `rc`. In the meantime, try using `npm3`.

I think we should just leave it `*` or skip entirely - @jordanbyron ?

**Comment by jordanbyron** [comment]
Ugh looks like this is a problem for a lot of people:

https://github.com/npm/npm/issues/8854

Personally I've never used rc versions of react native and I don't want to have to pull down the source, add a `| VERSION-RC` to the peerdependency, create a new release and then publish it ... every few weeks when a rc is released. 

Instead I suggest you use `npm install /path/to/your/fork` to get a working version in your project. It's not awesome, but you only have to deal with that while you're on a rc which isn't too bad.

**Comment by ababol** [comment]
Yeah I am using a rc version because I need the ART library which seems available only from 0.15.x.

So until the official release, I am fine by just using my fork ;).

Thanks guy and great job with this module btw! :+1:

**Comment by grabbou** [comment]
You can use ART without it, I am using it on 0.14. See documentation of react-native-progress where it has been described ;)

**Pull request closed without merging**
